### ISSUE TITLE
prerequisites fails

### ISSUE THREAD

**Issue by StevenACoffman** [braz/learnyoumongodb#2]
Hello,
If I run `learnyoumongodb prerequisites`, I get this error:

```
/usr/local/lib/node_modules/learnyoumongodb/node_modules/workshopper/workshopper.js:63
    return this._printPrerequisities()
                ^
TypeError: undefined is not a function
    at Workshopper.init (/usr/local/lib/node_modules/learnyoumongodb/node_modules/workshopper/workshopper.js:63:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/learnyoumongodb/learnyoumongodb.js:13:4)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:124:16)
    at node.js:842:3
```

**Comment by braz** [comment]
Hi Steven,
This isn't supported and I'll look into updating to see if the latest (1.4.1) Workshopper will handle the error case. If you run learnyoumongodb and navigate to the prerequisites then you can find out what they are. The associated libraries requires are in the package.json file for the module.
Hope this helps.
Eoin

**Comment by StevenACoffman** [comment]
When you select any exercise, it suggests the unsupported command (after the hint):

```
 » For any set up/installion prerequisites for learnyoumongodb, run:
   `learnyoumongodb prerequisites`.
```

I appreciated your exercise, so thanks for doing this. Also, as a suggestion, you might want to cross list this on the nodeschool website, as it gets more traffic.
